README.md
src/fetch.ts
test/index.test.ts

feat: support automatic json body for post requests

---

src/fetch.ts
test/index.test.mjs

Removes further baseURL appends when retrying.
closes #24

fix: remove baseurl append on retry

---

src/fetch.ts

This fixes #26.
A single line is changed, to wrap the call to `Error.captureStackTrace(err, $fetchRaw)` in a existence-check, as other libraries do to maintain compatibility with non-Chromium browsers.

fix: add check for using `Error.captureStackTrace`

---

README.md
src/fetch.ts
test/index.test.mjs

Some API (like https://github.com/login/oauth/access_token) needs `POST` and expect an `Accept: application/json` header to return json.
See https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github
When no using the `Accept` headers, it sends back:
```
error=bad_verification_code&error_description=The+code+passed+is+incorrect+or+expired.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23bad-verification-code
```

fix: add accept header when using json payload

---

README.md
package.json
src/fetch.ts
src/utils.ts
test/index.test.mjs
yarn.lock

resolves  #38
For binary content types, `$fetch` will instead return a `Blob` object.
You can optionally specify `blob`, `arrayBuffer` or `text` to force parsing the body with the respective `FetchResponse` method.
```js
// Use JSON.parse
await $fetch('/movie?lang=en', { parseResponse: JSON.parse })
// Return text as is
await $fetch('/movie?lang=en', { parseResponse: txt => txt })
// Get the blob version of the response
await $fetch('/api/generate-image', { responseType: 'blob' })
```
```ts
$fetch('api') // Promise<any>
$fetch<boolean>('api') // Promise<boolean>
$fetch<boolean>('api', { responseType: 'text' }) // Type '"text"' is not assignable to type '"json" | undefined'.ts(2322)
$fetch('api', { responseType: 'json' }) // Promise<any>
$fetch<boolean>('api', { responseType: 'json' }) // …
```

feat: return blob if `content-type` isn't text, svg, xml or json

---

src/fetch.ts
test/index.test.ts

Previously, everything that looked like it could be serialized, was actually serialized, no matter what content type was set.
This includes arbitrary strings. When you tried to send a string like `key "myval"` to the server using ohmyfetch, the server received `"key \\"myval\\""`.
Closes #58

fix: only serialize JSON bodies

---

src/fetch.ts
test/index.test.ts

Stop automatic retry by judging the wrong name【AbortError】、
https://developer.mozilla.org/en-US/docs/Web/API/DOMException#error_names

fix: do not  retry when fetch is aborted

---

README.md
src/fetch.ts
test/index.test.ts

refactor: add `query` alias to `params` option

---

src/fetch.ts
src/utils.ts

feat: support `responseType: 'stream'` as `ReadableStream`

---

src/fetch.ts

My English is not good, sorry I used a translator
Hi hello, I am using onRequest in $fetch.create in nuxt3, it throws an error, need to return a Promise? But I don't return anything and it seems to be working fine.
maybe it is possible to use union types to avoid this type error?
resolves https://github.com/unjs/ohmyfetch/issues/127

fix(types): allow synchronous interceptors to be passed

---

README.md

add agent option usage on docs. close #161

docs: add agent option usage

---

src/error.ts

The error message itself looks erroneous when the fetch fails without any request or response. Usually a network error. This can happen when a user disconnects from the internet or a fetch endpoint has an invalid ssl certfiicate.
Previously the message would be `Failed to Fetch ()` with these empty brackets.
Simple refactor to build the message up in the order that the final string will be and include the brackets only if required.
Thanks for all your work on this project! It's great.

fix: improve error message for request errors

---

cjs/index.cjs
cjs/node.cjs
package.json

Resolves #198
Resolves #44
Thanks to [node-fetch-native](https://github.com/unjs/node-fetch-native), we can have standalone CJS build without dist mocks

build: use standalone commonjs dist

---

README.md

Following https://github.com/unjs/ofetch/pull/49 the README should be updated accordingly.

docs(readme): use `_data` rather than `data` for raw requests

---

README.md

In `fetch.ts`, the `DELETE` method `retries` default also is **0**
https://github.com/unjs/ofetch/blob/9a5cd33b568ef70f476bda647cd43b1040aaa479/src/fetch.ts#L99
https://github.com/unjs/ofetch/blob/9a5cd33b568ef70f476bda647cd43b1040aaa479/src/utils.ts#L1-L6

docs: mention `DELETE` is no-retry be default

---

src/fetch.ts

ofetch crashes in Chrome 49 (which is the latest available Chrome on Windows XP which is still relevant in certain GovTech) with this message:
```
Failed to construct 'Headers': No matching constructor signature.
```
This is because older Chrome didn't treat `new Headers(undefined)` as `new Headers()`.
This PR fixes this inconvenience with no noticeable burden for modern browsers (or code base readability).
Related: https://github.com/whatwg/fetch/issues/185

fix: pass empty object to headers initializer to prevent crash on chrome 49

---

src/utils.ts

This re-exports the `ResponseMap` type. The use case for this is to allow consumers to build a type-safe variant of `ofetch` such we can append methods to a given instance.
Consider this wrapper library below called `api.ts`. In the code below, the `FetchOptions` type from `ofetch` consumes the private type `ResponseMap`. Building declarations for `api.ts` types for this would fail because the `ResponseMap` type is private to `ofetch`. In this case, re-exporting the type fixes the error and declarations can be built in userland.
```ts
// api.ts lib
import { ofetch, FetchOptions } from "ofetch";
export const $fetch = ofetch.create({
baseURL: SOME_API_BASE_URL,
headers: {
Accept: "application/json",
"Content-Type": "application/json",
},
onRequest(context) {
console.log("context", …
```

feat: export `ResponseMap` type to allow composition of `ofetch`

---

src/fetch.ts
test/index.test.ts

This is an attempt to fix the issue highlighted in nuxt/nuxt#19245 and [nuxt/nuxt#19245/issuecomment-1575671354](https://github.com/nuxt/nuxt/issues/19245#issuecomment-1575671354).

fix: fix issues with native node fetch

---

README.md
src/fetch.ts
test/index.test.ts

This is pretty straight forward if I did not miss something
Resolves  #207

feat: support `ignoreResponseError` option

---

src/fetch.ts
src/utils.ts
test/index.test.ts

**Problem**
If a fetch instance is created with default header options, and that instance is then called with more headers the default headers are overwritten. The same goes for the `param` and `query` properties.
```
const createdFetch = $fetch.create({
headers: {
"Header-Default": "1",
}
});
createdFetch("/some-url", {
headers: {
"Header-Request": "1",
}
});
```
The outgoing request should have both the `Header-Request` and `Header-Default` headers, but will only contain the former.
**Fix**
Merging the `headers`, `params` and `query` properties of the `FetchOptions` object before fetching fixes this issue. A more generic deep merge approach was tried, but merging other properties such as the body makes little sense.

fix: deep merge fetch options

---

README.md

Issue #263 .
Added an explanation in which cases retries occurs to avoid confusion.

docs: clarify retry behavior

---

README.md
src/fetch.ts
test/index.test.ts

https://github.com/unjs/nitro/pull/1534
Resolves #261 
Implements a `retryDelay` parameters that default to 100ms.

feat: support `retryDelay`

---

node.d.cts
package.json
pnpm-lock.yaml

close #251 
Sorry for the previous PR, I didn't know if the `type` was necessary, so I made a simple fix that removed it.
there is an awesome tool to check `exports` https://arethetypeswrong.github.io/ :
<table border="0">
<tr>
<td><b style="font-size:30px">Before</b></td>
<td><b style="font-size:30px">After</b></td>
</tr>
<tr>
<td><img src="https://github.com/unjs/ofetch/assets/13805071/1f2dffbd-6dcf-4a5e-86ae-c1767768a9e6" /></td>
<td><img src="https://github.com/unjs/ofetch/assets/13805071/1322c360-4649-4284-b0de-ddd31fef9268" /></td>
</tr>
</table>
References: [Masquerading as ESM](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md#common-causes)

fix(pkg): fix ts type resolution for `/node` subpath

---

README.md
src/fetch.ts
src/index.ts
src/node.ts
test/index.test.ts

Issue #21 
Added timeout feature.
Added timeoutExponent parameter to specify function to increase timeout over retries.
Added test for new feature.
Added documentation for new feature(maybe need fixes, sorry for my english).

feat: support `timeout` and `AbortController`

---

src/utils.ts
test/index.test.ts

resolves #269
Normally we allow serializing pure objects (with object constructor) OR classes that implement `toJSON()`.
However Buffer type is different and implements a `toJSON` method which is mainly for debugging.
This PR detects buffer type without depending on global `Buffer` as (Node.js) workaround 
Note: Worth to mention that other `BodyInit` compatible types such as `UInt8Array` do not share this issue as do not implement `toJSON`. We might consider detecting them explicitly if any runtime in the feature does. (-- Investigating Readable Body stream in next steps, current check currently allows it to be unserialized --)

fix: avoid serializing body with buffer type

---

package.json
pnpm-lock.yaml
src/fetch.ts
test/index.test.ts

This PR enables to support of stream request bodies (ReadableStream and Readable) out of the box by setting (semi standard?!) `duplex: 'half'` option. 
Limitations:
- This feature is only supported with native node fetch (Node.js 18+)
- For some reason, i couldn't enable `"transformed-encoding": "chunked"` and was causing the unsupported error. Therefore in tests, an explicit `content-length` is set (which i guess ideally we should not need)

feat: automatically enable duplex to stream request body

---

src/error.ts

#278
With the latest ofetch version, the `FetchError` does implement the `IFetchError` interface, but TS won't provide the types. Thus, only `message`, `stack` etc. properties are available.
Since the `FetchError` will be initiated by `createFetchError`, we can add the properties from the interface directly in the class definition, without the need of setting them in the constructor. With these changes, TypeScript understands.

fix: augment `FetchError` type to include `IFetchError`

---

src/error.ts
src/fetch.ts
src/index.ts
src/types.ts
src/utils.ts

I'm building a library around ofetch that needs defines custom fetch functions with the same signature as ofetch, so ideally I would have access to these types to define the function. My current workaround is to copy-paste the types into the library but this doesn't feel quite right.
If there's a reason for these types to not be exported, just close this PR and I will stick to the workaround 👍🏼

feat: export all types

---

src/index.ts
src/types.ts

Resolves #302
This PR exposes `SharedOptions` type, a sub type of `FetchOptions` that is completely safe to be shared in reusable instances via global configuration.  (currently timeout, retry and retryDelay) other things in the future such as respectProxy might be included.
The border between choosing if something is safe to be global option or not is that it should not affect any runtime logic behavior changes.

feat: expose `GlobalOptions` type

---

src/fetch.ts

#361
Resolves #361.
Alternative PR to #362. Changes:
- Didn't apply formatting
- Clear timeout immediately after request, not after it's parsing

fix: clear abort timeout after response was received

---

src/fetch.ts

N/A
The current code is as follows:
```ts
$fetchRaw(context.request, {
...context.options,
retry: retries - 1,
timeout: context.options.timeout,
});
```
Based on the context, the `timeout: context.options.timeout` part should not be duplicated, so this PR tries to remove it.

refactor: remove useless code

---

src/fetch.ts

chore: remove extra space

---

README.md

#379, #215, #316
`agent` setting only applies to older versions of node.
As of version 18 node fetch is native and depends on `undici`, which uses a `dispatcher` option instead

docs: add docs for using undici dispatcher

---

src/fetch.ts
src/types.ts
test/index.test.ts

Calculate retry delay based on context. 
Opens possibility to make retries with incremental delay. For example:
```typescript
{
retry: 3,
retryDelay: (context) => {
const attempt = context.options.retryAttempt = (context.options.retryAttempt || 0) + 1;
return 300 * (Math.pow(3, attempt - 1))
},
}
```

feat: support `retryDelay` with callback function

---

src/node.ts

Looking at resolving type issues in https://github.com/nuxt/nuxt/pull/27702, it seems we don't have types exported from `node` declarations in `ofetch`, which means they can't be resolved/imported in some environments.

fix: export types from `node` export condition

---

README.md
src/fetch.ts

425 Too Early status is still experimental technology. I think may be adding experimental could be good for understanding.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Early-Data
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

chore: add experimental for `Too Early` status

---

src/fetch.ts
src/types.ts

#71
This commit adds an optional parameter `globalOptionsOverwrite`  to  `$fetch.create`.  
However, for HTTP, headers are not case-sensitive. But for some reason, headers are case-sensitive in some old backend frameworks. This optional parameter overrides native `Headers` behaviour in such situations.
As only adding an optional parameter, it won`t break anything, maybe?

feat: allow custom global options for `$fetch.create`

---

src/fetch.ts
src/types.ts
src/utils.ts
test/index.test.ts

resolves #393
This PR adds a change to always normalize `context.options.headers` into a `Headers` object and making sure it is also cloned. 
Additional fixes: 
- If first param to ofetch is a Request, and there is no headers option, it's headers will be used (same as fetch behavior)
- `query` and `params` are now consistent and normalized to the same object.

feat: always clone and normalize `options.headers` and `options.query`

---

test/index.test.ts

Looks like line 428 is supposed to be 'onResponse' rather than 'onRequest'.

test: fix typo

---

src/fetch.ts
test/index.test.ts

Context: https://github.com/nuxt/nuxt/pull/29052
> fetch manifest.json in chrome 63. Request method has no default value at ofetch lib, it will returen 400 Bad reuqest.
I haven't tested on legacy Chrome versions and it seems something we don't need to by spec but for the sake of simplicity.

fix: remove undefined `method` and `query`/`params` from fetch options

---

src/fetch.ts

Fixes #324 
This pr is essentially a one line change to add react native support. It checks `response._bodyInit` in addition to `response.body` to see if a body exists in the response.
Normally I would say that this is an upstream issue that react native should fix, but the reality is fetch has not been spec compliant in react native for a long time, and it doesn't seem like there has been any meaningful progress in that department either. So I don't think it's practical to wait on them. 
I would also argue that even though this is a runtime specific check it shouldn't add any overhead for maintainers because its such a small change. I've also included comments explaining what the additional `_bodyInit` check is for and under what conditions it can be removed.
Additionally this repo does …

fix: use  `response._bodyInit` as fallback for react-native and qq

---

README.md

Changed `Agent` to `ProxyAgent` in the READMEs self-signed certificate example. This changes should help with consistency, as all other examples use the `ProxyAgent` and the `Agent` misses a lot of essential proxy functionality that would probably be used in combination with self-signed certs like the `uri` option.

docs(readme):  use `ProxyAgent` in example

---

README.md
examples/error-handling.mjs

chore: fix typos

---

src/utils.ts

resolves #439
resolves #466
Bun added `toJSON` method to `URLSearchParams` and `FormData`, this confused the `isJSONSerializable`.
It’s neither Node.js behavior (Bun aims for 100% compatibility) nor standard behavior (according to MDN)

fix: mark `FormData` & `URLSearchParams` as non-serializable for bun compatibility

---

src/fetch.ts
test/index.test.ts

…orm-urlencoded`
resolves #425

feat: serialize with `URLSearchParams` for `application/x-www-form-urlencoded` content type header
